import { Cluster, Politica, Segmento } from "../interfaces/parametrizador.interface";

export const segmentos: Segmento[] = [
    { id: 1, nome: "Segmento 1", descricao: "Segmento 1 - Descrição 1", isAtivo: true },
    { id: 2, nome: "Segmento 2", descricao: "Segmento 2 - Descrição 2", isAtivo: false },
    { id: 3, nome: "Segmento 3", descricao: "Segmento 3 - Descrição 3", isAtivo: true },
    { id: 4, nome: "Segmento 4", descricao: "Segmento 4 - Descrição 4", isAtivo: false },
    { id: 5, nome: "Segmento 5", descricao: "Segmento 5 - Descrição 5", isAtivo: true }
];

export const clusters: Cluster[] = [
    { id: 1, nome: "Cluster 1", descricao: "Cluster 1 - Descrição 1", isAtivo: true, segmento: segmentos[0] },
    { id: 2, nome: "Cluster 2", descricao: "Cluster 2 - Descrição 2", isAtivo: false, segmento: segmentos[0] },
    { id: 3, nome: "Cluster 3", descricao: "Cluster 3 - Descrição 3", isAtivo: true, segmento: segmentos[0] },
    { id: 4, nome: "Cluster 4", descricao: "Cluster 4 - Descrição 4", isAtivo: false, segmento: segmentos[1] },
    { id: 5, nome: "Cluster 5", descricao: "Cluster 5 - Descrição 5", isAtivo: true, segmento: segmentos[1] },
    { id: 6, nome: "Cluster 6", descricao: "Cluster 6 - Descrição 6", isAtivo: false, segmento: segmentos[1] },
    { id: 7, nome: "Cluster 7", descricao: "Cluster 7 - Descrição 7", isAtivo: true, segmento: segmentos[2] },
    { id: 8, nome: "Cluster 8", descricao: "Cluster 8 - Descrição 8", isAtivo: false, segmento: segmentos[2] },
    { id: 9, nome: "Cluster 9", descricao: "Cluster 9 - Descrição 9", isAtivo: true, segmento: segmentos[2] },
    { id: 10, nome: "Cluster 10", descricao: "Cluster 10 - Descrição 10", isAtivo: false, segmento: segmentos[3] },
    { id: 11, nome: "Cluster 11", descricao: "Cluster 11 - Descrição 11", isAtivo: true, segmento: segmentos[3] },
    { id: 12, nome: "Cluster 12", descricao: "Cluster 12 - Descrição 12", isAtivo: false, segmento: segmentos[3] },
    { id: 13, nome: "Cluster 13", descricao: "Cluster 13 - Descrição 13", isAtivo: true, segmento: segmentos[4] },
    { id: 14, nome: "Cluster 14", descricao: "Cluster 14 - Descrição 14", isAtivo: false, segmento: segmentos[4] },
    { id: 15, nome: "Cluster 15", descricao: "Cluster 15 - Descrição 15", isAtivo: true, segmento: segmentos[4] }
];

export const politicas: Politica[] = [
    { id: 1, nome: "Politica 1", isAtivo: true, cluster: clusters[0] },
    { id: 2, nome: "Politica 2", isAtivo: false, cluster: clusters[0] },
    { id: 3, nome: "Politica 3", isAtivo: true, cluster: clusters[0] },
    { id: 4, nome: "Politica 4", isAtivo: false, cluster: clusters[1] },
    { id: 5, nome: "Politica 5", isAtivo: true, cluster: clusters[1] },
    { id: 6, nome: "Politica 6", isAtivo: false, cluster: clusters[1] },
    { id: 7, nome: "Politica 7", isAtivo: true, cluster: clusters[2] },
    { id: 8, nome: "Politica 8", isAtivo: false, cluster: clusters[2] },
    { id: 9, nome: "Politica 9", isAtivo: true, cluster: clusters[2] },
    { id: 10, nome: "Politica 10", isAtivo: false, cluster: clusters[3] },
    { id: 11, nome: "Politica 11", isAtivo: true, cluster: clusters[3] },
    { id: 12, nome: "Politica 12", isAtivo: false, cluster: clusters[3] },
    { id: 13, nome: "Politica 13", isAtivo: true, cluster: clusters[4] },
    { id: 14, nome: "Politica 14", isAtivo: false, cluster: clusters[4] },
    { id: 15, nome: "Politica 15", isAtivo: true, cluster: clusters[4] },
    { id: 16, nome: "Politica 16", isAtivo: false, cluster: clusters[5] },
    { id: 17, nome: "Politica 17", isAtivo: true, cluster: clusters[5] },
    { id: 18, nome: "Politica 18", isAtivo: false, cluster: clusters[5] },
    { id: 19, nome: "Politica 19", isAtivo: true, cluster: clusters[6] },
    { id: 20, nome: "Politica 20", isAtivo: false, cluster: clusters[6] },
    { id: 21, nome: "Politica 21", isAtivo: true, cluster: clusters[6] },
    { id: 22, nome: "Politica 22", isAtivo: false, cluster: clusters[7] },
    { id: 23, nome: "Politica 23", isAtivo: true, cluster: clusters[7] },
    { id: 24, nome: "Politica 24", isAtivo: false, cluster: clusters[7] },
    { id: 25, nome: "Politica 25", isAtivo: true, cluster: clusters[8] },
    { id: 26, nome: "Politica 26", isAtivo: false, cluster: clusters[8] },
    { id: 27, nome: "Politica 27", isAtivo: true, cluster: clusters[8] },
    { id: 28, nome: "Politica 28", isAtivo: false, cluster: clusters[9] },
    { id: 29, nome: "Politica 29", isAtivo: true, cluster: clusters[9] },
    { id: 30, nome: "Politica 30", isAtivo: false, cluster: clusters[9] },
    { id: 31, nome: "Politica 31", isAtivo: true, cluster: clusters[10] },
    { id: 32, nome: "Politica 32", isAtivo: false, cluster: clusters[10] },
    { id: 33, nome: "Politica 33", isAtivo: true, cluster: clusters[10] },
    { id: 34, nome: "Politica 34", isAtivo: false, cluster: clusters[11] },
    { id: 35, nome: "Politica 35", isAtivo: true, cluster: clusters[11] },
    { id: 36, nome: "Politica 36", isAtivo: false, cluster: clusters[11] },
    { id: 37, nome: "Politica 37", isAtivo: true, cluster: clusters[12] },
    { id: 38, nome: "Politica 38", isAtivo: false, cluster: clusters[12] },
    { id: 39, nome: "Politica 39", isAtivo: true, cluster: clusters[12] },
    { id: 40, nome: "Politica 40", isAtivo: false, cluster: clusters[13] },
    { id: 41, nome: "Politica 41", isAtivo: true, cluster: clusters[13] },
    { id: 42, nome: "Politica 42", isAtivo: false, cluster: clusters[13] },
    { id: 43, nome: "Politica 43", isAtivo: true, cluster: clusters[14] },
    { id: 44, nome: "Politica 44", isAtivo: false, cluster: clusters[14] },
    { id: 45, nome: "Politica 45", isAtivo: true, cluster: clusters[14] }
];